### ISSUE TITLE
Request: Add TerraFirmaCraft 1.12.2 compatibility

### ISSUE THREAD

**Issue by Pentasis** [primetoxinz/CoralReef#15]
The coral reefs do not spawn in tfc:ocean and tfc:deep_ocean biomes, despite me setting them in the config. I suspect this is because TFC uses its own water blocks (fresh_water & salt_water) instead of the vanilla water.
Would you consider adding compatibility?

**Comment by Fotrik-cz** [comment]
i want it too pls
