### ISSUE TITLE
missing texture?

### ISSUE THREAD

**Issue by jprocket45** [primetoxinz/CoralReef#9]
Orange Coral reef has no texture just black/purple block  Forge ver 2611

**Comment by jprocket45** [comment]
[https://imgur.com/XK9PU8z](url)

**Comment by jprocket45** [comment]
[<a href="https://imgur.com/XK9PU8z"><img src="https://i.imgur.com/XK9PU8z.jpg" title="source: imgur.com" /></a>](url)

**Comment by primetoxinz** [comment]
Been busy, working on getting this fixed.

**Comment by primetoxinz** [comment]
Fixed in 2.4, it will be on Curse shortly
